apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: api-cert-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"    # 관리 ID를 사용하는 경우 true로 설정
    userAssignedIdentityID: "SecretProviderClass 호스팅 노드 풀 관리 ID 클라이언트ID" # SecretProviderClass 호스팅 노드 풀 관리 ID 클라이언트ID
    keyvaultName: "kv-aks-https"    # Key Vault 이름
    objects: |
      array:
        - |
          objectType: secret        # Key Vault에서 가져올 타입
          objectName: wildcard-cert # 이름
    tenantId: "Key Vault의 테넌트ID" # Key Vault의 테넌트ID
  # K8s Secret 변환 설정(CSI 드라이버에 의해 tls.key, tls.crt 데이터로 추출됨)
  secretObjects:
    - secretName: api-cert-tls-secret # Ingress에서 사용할 시크릿 이름
      type: kubernetes.io/tls
      data:
        - objectName: wildcard-cert
          key: tls.key # certbot 인증서 발급 결과: privkey.pem(개인키)
        - objectName: wildcard-cert
          key: tls.crt # certbot 인증서 발급 결과: fullchain.pem(공개 인증서 + 보증기관 중개 인증서)
