apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-dummy-sa
  namespace: default
  annotations:
    azure.workload.identity/client-id: "<관리ID의 클라이언트ID>" # 이 서비스어카운트와 페더레이션 자격 증명이 설정된 관리 ID의 클라이언트 ID
  labels:
    azure.workload.identity/use: "true" # Workload Identity 인증 방식 사용